// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana
{
    [GrafanaResourceType("grafana:index/dashboard:Dashboard")]
    public partial class Dashboard : Pulumi.CustomResource
    {
        /// <summary>
        /// The complete dashboard model JSON.
        /// </summary>
        [Output("configJson")]
        public Output<string> ConfigJson { get; private set; } = null!;

        /// <summary>
        /// The numeric ID of the dashboard computed by Grafana.
        /// </summary>
        [Output("dashboardId")]
        public Output<int> DashboardId { get; private set; } = null!;

        /// <summary>
        /// The id of the folder to save the dashboard in.
        /// </summary>
        [Output("folder")]
        public Output<int?> Folder { get; private set; } = null!;

        /// <summary>
        /// URL friendly version of the dashboard title.
        /// </summary>
        [Output("slug")]
        public Output<string> Slug { get; private set; } = null!;


        /// <summary>
        /// Create a Dashboard resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Dashboard(string name, DashboardArgs args, CustomResourceOptions? options = null)
            : base("grafana:index/dashboard:Dashboard", name, args ?? new DashboardArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Dashboard(string name, Input<string> id, DashboardState? state = null, CustomResourceOptions? options = null)
            : base("grafana:index/dashboard:Dashboard", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Dashboard resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Dashboard Get(string name, Input<string> id, DashboardState? state = null, CustomResourceOptions? options = null)
        {
            return new Dashboard(name, id, state, options);
        }
    }

    public sealed class DashboardArgs : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The complete dashboard model JSON.
        /// </summary>
        [Input("configJson", required: true)]
        public Input<string> ConfigJson { get; set; } = null!;

        /// <summary>
        /// The id of the folder to save the dashboard in.
        /// </summary>
        [Input("folder")]
        public Input<int>? Folder { get; set; }

        public DashboardArgs()
        {
        }
    }

    public sealed class DashboardState : Pulumi.ResourceArgs
    {
        /// <summary>
        /// The complete dashboard model JSON.
        /// </summary>
        [Input("configJson")]
        public Input<string>? ConfigJson { get; set; }

        /// <summary>
        /// The numeric ID of the dashboard computed by Grafana.
        /// </summary>
        [Input("dashboardId")]
        public Input<int>? DashboardId { get; set; }

        /// <summary>
        /// The id of the folder to save the dashboard in.
        /// </summary>
        [Input("folder")]
        public Input<int>? Folder { get; set; }

        /// <summary>
        /// URL friendly version of the dashboard title.
        /// </summary>
        [Input("slug")]
        public Input<string>? Slug { get; set; }

        public DashboardState()
        {
        }
    }
}
