// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class BuiltinRoleAssignmentRole
    {
        public readonly bool? Global;
        public readonly string Uid;

        [OutputConstructor]
        private BuiltinRoleAssignmentRole(
            bool? global,

            string uid)
        {
            Global = global;
            Uid = uid;
        }
    }
}
