// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class DataSourceJsonData
    {
        public readonly string? AssumeRoleArn;
        public readonly string? AuthType;
        public readonly string? AuthenticationType;
        public readonly string? ClientEmail;
        public readonly int? ConnMaxLifetime;
        public readonly string? CustomMetricsNamespaces;
        public readonly string? DefaultProject;
        public readonly string? DefaultRegion;
        public readonly string? Encrypt;
        public readonly int? EsVersion;
        public readonly string? GraphiteVersion;
        public readonly string? HttpMethod;
        public readonly string? Interval;
        public readonly string? LogLevelField;
        public readonly string? LogMessageField;
        public readonly int? MaxIdleConns;
        public readonly int? MaxOpenConns;
        public readonly int? PostgresVersion;
        public readonly string? Profile;
        public readonly string? QueryTimeout;
        public readonly string? SslMode;
        public readonly string? TimeField;
        public readonly string? TimeInterval;
        public readonly bool? Timescaledb;
        public readonly bool? TlsAuth;
        public readonly bool? TlsAuthWithCaCert;
        public readonly bool? TlsSkipVerify;
        public readonly string? TokenUri;
        public readonly string? TsdbResolution;
        public readonly string? TsdbVersion;

        [OutputConstructor]
        private DataSourceJsonData(
            string? assumeRoleArn,

            string? authType,

            string? authenticationType,

            string? clientEmail,

            int? connMaxLifetime,

            string? customMetricsNamespaces,

            string? defaultProject,

            string? defaultRegion,

            string? encrypt,

            int? esVersion,

            string? graphiteVersion,

            string? httpMethod,

            string? interval,

            string? logLevelField,

            string? logMessageField,

            int? maxIdleConns,

            int? maxOpenConns,

            int? postgresVersion,

            string? profile,

            string? queryTimeout,

            string? sslMode,

            string? timeField,

            string? timeInterval,

            bool? timescaledb,

            bool? tlsAuth,

            bool? tlsAuthWithCaCert,

            bool? tlsSkipVerify,

            string? tokenUri,

            string? tsdbResolution,

            string? tsdbVersion)
        {
            AssumeRoleArn = assumeRoleArn;
            AuthType = authType;
            AuthenticationType = authenticationType;
            ClientEmail = clientEmail;
            ConnMaxLifetime = connMaxLifetime;
            CustomMetricsNamespaces = customMetricsNamespaces;
            DefaultProject = defaultProject;
            DefaultRegion = defaultRegion;
            Encrypt = encrypt;
            EsVersion = esVersion;
            GraphiteVersion = graphiteVersion;
            HttpMethod = httpMethod;
            Interval = interval;
            LogLevelField = logLevelField;
            LogMessageField = logMessageField;
            MaxIdleConns = maxIdleConns;
            MaxOpenConns = maxOpenConns;
            PostgresVersion = postgresVersion;
            Profile = profile;
            QueryTimeout = queryTimeout;
            SslMode = sslMode;
            TimeField = timeField;
            TimeInterval = timeInterval;
            Timescaledb = timescaledb;
            TlsAuth = tlsAuth;
            TlsAuthWithCaCert = tlsAuthWithCaCert;
            TlsSkipVerify = tlsSkipVerify;
            TokenUri = tokenUri;
            TsdbResolution = tsdbResolution;
            TsdbVersion = tsdbVersion;
        }
    }
}
