// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class DataSourceSecureJsonData
    {
        public readonly string? AccessKey;
        public readonly string? BasicAuthPassword;
        public readonly string? Password;
        public readonly string? PrivateKey;
        public readonly string? SecretKey;
        public readonly string? TlsCaCert;
        public readonly string? TlsClientCert;
        public readonly string? TlsClientKey;

        [OutputConstructor]
        private DataSourceSecureJsonData(
            string? accessKey,

            string? basicAuthPassword,

            string? password,

            string? privateKey,

            string? secretKey,

            string? tlsCaCert,

            string? tlsClientCert,

            string? tlsClientKey)
        {
            AccessKey = accessKey;
            BasicAuthPassword = basicAuthPassword;
            Password = password;
            PrivateKey = privateKey;
            SecretKey = secretKey;
            TlsCaCert = tlsCaCert;
            TlsClientCert = tlsClientCert;
            TlsClientKey = tlsClientKey;
        }
    }
}
