// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Outputs
{

    [OutputType]
    public sealed class RolePermission
    {
        public readonly string Action;
        public readonly string? Scope;

        [OutputConstructor]
        private RolePermission(
            string action,

            string? scope)
        {
            Action = action;
            Scope = scope;
        }
    }
}
