# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .alert_notification import *
from .builtin_role_assignment import *
from .dashboard import *
from .dashboard_permission import *
from .data_source import *
from .folder import *
from .folder_permission import *
from .organization import *
from .provider import *
from .role import *
from .team import *
from .team_preferences import *
from .user import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_grafana.config as config
else:
    config = _utilities.lazy_import('pulumi_grafana.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "grafana",
  "mod": "index/alertNotification",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/alertNotification:AlertNotification": "AlertNotification"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/builtinRoleAssignment",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/builtinRoleAssignment:BuiltinRoleAssignment": "BuiltinRoleAssignment"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/dashboard",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/dashboard:Dashboard": "Dashboard"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/dashboardPermission",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/dashboardPermission:DashboardPermission": "DashboardPermission"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/dataSource",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/dataSource:DataSource": "DataSource"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/folder",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/folder:Folder": "Folder"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/folderPermission",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/folderPermission:FolderPermission": "FolderPermission"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/organization",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/organization:Organization": "Organization"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/role",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/role:Role": "Role"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/team",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/team:Team": "Team"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/teamPreferences",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/teamPreferences:TeamPreferences": "TeamPreferences"
  }
 },
 {
  "pkg": "grafana",
  "mod": "index/user",
  "fqn": "pulumi_grafana",
  "classes": {
   "grafana:index/user:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "grafana",
  "token": "pulumi:providers:grafana",
  "fqn": "pulumi_grafana",
  "class": "Provider"
 }
]
"""
)
