// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface BuiltinRoleAssignmentRole {
    global?: boolean;
    uid: string;
}

export interface DashboardPermissionPermission {
    permission: string;
    role?: string;
    teamId?: number;
    userId?: number;
}

export interface DataSourceJsonData {
    assumeRoleArn?: string;
    authType?: string;
    authenticationType?: string;
    clientEmail?: string;
    connMaxLifetime?: number;
    customMetricsNamespaces?: string;
    defaultProject?: string;
    defaultRegion?: string;
    encrypt?: string;
    esVersion?: number;
    graphiteVersion?: string;
    httpMethod?: string;
    interval?: string;
    logLevelField?: string;
    logMessageField?: string;
    maxIdleConns?: number;
    maxOpenConns?: number;
    postgresVersion?: number;
    profile?: string;
    queryTimeout?: string;
    sslMode?: string;
    timeField?: string;
    timeInterval?: string;
    timescaledb?: boolean;
    tlsAuth?: boolean;
    tlsAuthWithCaCert?: boolean;
    tlsSkipVerify?: boolean;
    tokenUri?: string;
    tsdbResolution?: string;
    tsdbVersion?: string;
}

export interface DataSourceSecureJsonData {
    accessKey?: string;
    basicAuthPassword?: string;
    password?: string;
    privateKey?: string;
    secretKey?: string;
    tlsCaCert?: string;
    tlsClientCert?: string;
    tlsClientKey?: string;
}

export interface FolderPermissionPermission {
    permission: string;
    role?: string;
    teamId?: number;
    userId?: number;
}

export interface RolePermission {
    action: string;
    scope?: string;
}

