// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package grafana

import (
	"context"
	"reflect"

	"github.com/pkg/errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type BuiltinRoleAssignment struct {
	pulumi.CustomResourceState

	BuiltinRole pulumi.StringOutput                  `pulumi:"builtinRole"`
	Roles       BuiltinRoleAssignmentRoleArrayOutput `pulumi:"roles"`
}

// NewBuiltinRoleAssignment registers a new resource with the given unique name, arguments, and options.
func NewBuiltinRoleAssignment(ctx *pulumi.Context,
	name string, args *BuiltinRoleAssignmentArgs, opts ...pulumi.ResourceOption) (*BuiltinRoleAssignment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.BuiltinRole == nil {
		return nil, errors.New("invalid value for required argument 'BuiltinRole'")
	}
	if args.Roles == nil {
		return nil, errors.New("invalid value for required argument 'Roles'")
	}
	var resource BuiltinRoleAssignment
	err := ctx.RegisterResource("grafana:index/builtinRoleAssignment:BuiltinRoleAssignment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetBuiltinRoleAssignment gets an existing BuiltinRoleAssignment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetBuiltinRoleAssignment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *BuiltinRoleAssignmentState, opts ...pulumi.ResourceOption) (*BuiltinRoleAssignment, error) {
	var resource BuiltinRoleAssignment
	err := ctx.ReadResource("grafana:index/builtinRoleAssignment:BuiltinRoleAssignment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering BuiltinRoleAssignment resources.
type builtinRoleAssignmentState struct {
	BuiltinRole *string                     `pulumi:"builtinRole"`
	Roles       []BuiltinRoleAssignmentRole `pulumi:"roles"`
}

type BuiltinRoleAssignmentState struct {
	BuiltinRole pulumi.StringPtrInput
	Roles       BuiltinRoleAssignmentRoleArrayInput
}

func (BuiltinRoleAssignmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*builtinRoleAssignmentState)(nil)).Elem()
}

type builtinRoleAssignmentArgs struct {
	BuiltinRole string                      `pulumi:"builtinRole"`
	Roles       []BuiltinRoleAssignmentRole `pulumi:"roles"`
}

// The set of arguments for constructing a BuiltinRoleAssignment resource.
type BuiltinRoleAssignmentArgs struct {
	BuiltinRole pulumi.StringInput
	Roles       BuiltinRoleAssignmentRoleArrayInput
}

func (BuiltinRoleAssignmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*builtinRoleAssignmentArgs)(nil)).Elem()
}

type BuiltinRoleAssignmentInput interface {
	pulumi.Input

	ToBuiltinRoleAssignmentOutput() BuiltinRoleAssignmentOutput
	ToBuiltinRoleAssignmentOutputWithContext(ctx context.Context) BuiltinRoleAssignmentOutput
}

func (*BuiltinRoleAssignment) ElementType() reflect.Type {
	return reflect.TypeOf((*BuiltinRoleAssignment)(nil))
}

func (i *BuiltinRoleAssignment) ToBuiltinRoleAssignmentOutput() BuiltinRoleAssignmentOutput {
	return i.ToBuiltinRoleAssignmentOutputWithContext(context.Background())
}

func (i *BuiltinRoleAssignment) ToBuiltinRoleAssignmentOutputWithContext(ctx context.Context) BuiltinRoleAssignmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuiltinRoleAssignmentOutput)
}

func (i *BuiltinRoleAssignment) ToBuiltinRoleAssignmentPtrOutput() BuiltinRoleAssignmentPtrOutput {
	return i.ToBuiltinRoleAssignmentPtrOutputWithContext(context.Background())
}

func (i *BuiltinRoleAssignment) ToBuiltinRoleAssignmentPtrOutputWithContext(ctx context.Context) BuiltinRoleAssignmentPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuiltinRoleAssignmentPtrOutput)
}

type BuiltinRoleAssignmentPtrInput interface {
	pulumi.Input

	ToBuiltinRoleAssignmentPtrOutput() BuiltinRoleAssignmentPtrOutput
	ToBuiltinRoleAssignmentPtrOutputWithContext(ctx context.Context) BuiltinRoleAssignmentPtrOutput
}

type builtinRoleAssignmentPtrType BuiltinRoleAssignmentArgs

func (*builtinRoleAssignmentPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**BuiltinRoleAssignment)(nil))
}

func (i *builtinRoleAssignmentPtrType) ToBuiltinRoleAssignmentPtrOutput() BuiltinRoleAssignmentPtrOutput {
	return i.ToBuiltinRoleAssignmentPtrOutputWithContext(context.Background())
}

func (i *builtinRoleAssignmentPtrType) ToBuiltinRoleAssignmentPtrOutputWithContext(ctx context.Context) BuiltinRoleAssignmentPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuiltinRoleAssignmentPtrOutput)
}

// BuiltinRoleAssignmentArrayInput is an input type that accepts BuiltinRoleAssignmentArray and BuiltinRoleAssignmentArrayOutput values.
// You can construct a concrete instance of `BuiltinRoleAssignmentArrayInput` via:
//
//          BuiltinRoleAssignmentArray{ BuiltinRoleAssignmentArgs{...} }
type BuiltinRoleAssignmentArrayInput interface {
	pulumi.Input

	ToBuiltinRoleAssignmentArrayOutput() BuiltinRoleAssignmentArrayOutput
	ToBuiltinRoleAssignmentArrayOutputWithContext(context.Context) BuiltinRoleAssignmentArrayOutput
}

type BuiltinRoleAssignmentArray []BuiltinRoleAssignmentInput

func (BuiltinRoleAssignmentArray) ElementType() reflect.Type {
	return reflect.TypeOf(([]*BuiltinRoleAssignment)(nil))
}

func (i BuiltinRoleAssignmentArray) ToBuiltinRoleAssignmentArrayOutput() BuiltinRoleAssignmentArrayOutput {
	return i.ToBuiltinRoleAssignmentArrayOutputWithContext(context.Background())
}

func (i BuiltinRoleAssignmentArray) ToBuiltinRoleAssignmentArrayOutputWithContext(ctx context.Context) BuiltinRoleAssignmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuiltinRoleAssignmentArrayOutput)
}

// BuiltinRoleAssignmentMapInput is an input type that accepts BuiltinRoleAssignmentMap and BuiltinRoleAssignmentMapOutput values.
// You can construct a concrete instance of `BuiltinRoleAssignmentMapInput` via:
//
//          BuiltinRoleAssignmentMap{ "key": BuiltinRoleAssignmentArgs{...} }
type BuiltinRoleAssignmentMapInput interface {
	pulumi.Input

	ToBuiltinRoleAssignmentMapOutput() BuiltinRoleAssignmentMapOutput
	ToBuiltinRoleAssignmentMapOutputWithContext(context.Context) BuiltinRoleAssignmentMapOutput
}

type BuiltinRoleAssignmentMap map[string]BuiltinRoleAssignmentInput

func (BuiltinRoleAssignmentMap) ElementType() reflect.Type {
	return reflect.TypeOf((map[string]*BuiltinRoleAssignment)(nil))
}

func (i BuiltinRoleAssignmentMap) ToBuiltinRoleAssignmentMapOutput() BuiltinRoleAssignmentMapOutput {
	return i.ToBuiltinRoleAssignmentMapOutputWithContext(context.Background())
}

func (i BuiltinRoleAssignmentMap) ToBuiltinRoleAssignmentMapOutputWithContext(ctx context.Context) BuiltinRoleAssignmentMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(BuiltinRoleAssignmentMapOutput)
}

type BuiltinRoleAssignmentOutput struct {
	*pulumi.OutputState
}

func (BuiltinRoleAssignmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*BuiltinRoleAssignment)(nil))
}

func (o BuiltinRoleAssignmentOutput) ToBuiltinRoleAssignmentOutput() BuiltinRoleAssignmentOutput {
	return o
}

func (o BuiltinRoleAssignmentOutput) ToBuiltinRoleAssignmentOutputWithContext(ctx context.Context) BuiltinRoleAssignmentOutput {
	return o
}

func (o BuiltinRoleAssignmentOutput) ToBuiltinRoleAssignmentPtrOutput() BuiltinRoleAssignmentPtrOutput {
	return o.ToBuiltinRoleAssignmentPtrOutputWithContext(context.Background())
}

func (o BuiltinRoleAssignmentOutput) ToBuiltinRoleAssignmentPtrOutputWithContext(ctx context.Context) BuiltinRoleAssignmentPtrOutput {
	return o.ApplyT(func(v BuiltinRoleAssignment) *BuiltinRoleAssignment {
		return &v
	}).(BuiltinRoleAssignmentPtrOutput)
}

type BuiltinRoleAssignmentPtrOutput struct {
	*pulumi.OutputState
}

func (BuiltinRoleAssignmentPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**BuiltinRoleAssignment)(nil))
}

func (o BuiltinRoleAssignmentPtrOutput) ToBuiltinRoleAssignmentPtrOutput() BuiltinRoleAssignmentPtrOutput {
	return o
}

func (o BuiltinRoleAssignmentPtrOutput) ToBuiltinRoleAssignmentPtrOutputWithContext(ctx context.Context) BuiltinRoleAssignmentPtrOutput {
	return o
}

type BuiltinRoleAssignmentArrayOutput struct{ *pulumi.OutputState }

func (BuiltinRoleAssignmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]BuiltinRoleAssignment)(nil))
}

func (o BuiltinRoleAssignmentArrayOutput) ToBuiltinRoleAssignmentArrayOutput() BuiltinRoleAssignmentArrayOutput {
	return o
}

func (o BuiltinRoleAssignmentArrayOutput) ToBuiltinRoleAssignmentArrayOutputWithContext(ctx context.Context) BuiltinRoleAssignmentArrayOutput {
	return o
}

func (o BuiltinRoleAssignmentArrayOutput) Index(i pulumi.IntInput) BuiltinRoleAssignmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) BuiltinRoleAssignment {
		return vs[0].([]BuiltinRoleAssignment)[vs[1].(int)]
	}).(BuiltinRoleAssignmentOutput)
}

type BuiltinRoleAssignmentMapOutput struct{ *pulumi.OutputState }

func (BuiltinRoleAssignmentMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]BuiltinRoleAssignment)(nil))
}

func (o BuiltinRoleAssignmentMapOutput) ToBuiltinRoleAssignmentMapOutput() BuiltinRoleAssignmentMapOutput {
	return o
}

func (o BuiltinRoleAssignmentMapOutput) ToBuiltinRoleAssignmentMapOutputWithContext(ctx context.Context) BuiltinRoleAssignmentMapOutput {
	return o
}

func (o BuiltinRoleAssignmentMapOutput) MapIndex(k pulumi.StringInput) BuiltinRoleAssignmentOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) BuiltinRoleAssignment {
		return vs[0].(map[string]BuiltinRoleAssignment)[vs[1].(string)]
	}).(BuiltinRoleAssignmentOutput)
}

func init() {
	pulumi.RegisterOutputType(BuiltinRoleAssignmentOutput{})
	pulumi.RegisterOutputType(BuiltinRoleAssignmentPtrOutput{})
	pulumi.RegisterOutputType(BuiltinRoleAssignmentArrayOutput{})
	pulumi.RegisterOutputType(BuiltinRoleAssignmentMapOutput{})
}
