// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package grafana

import (
	"fmt"

	"github.com/blang/semver"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type module struct {
	version semver.Version
}

func (m *module) Version() semver.Version {
	return m.version
}

func (m *module) Construct(ctx *pulumi.Context, name, typ, urn string) (r pulumi.Resource, err error) {
	switch typ {
	case "grafana:index/alertNotification:AlertNotification":
		r = &AlertNotification{}
	case "grafana:index/builtinRoleAssignment:BuiltinRoleAssignment":
		r = &BuiltinRoleAssignment{}
	case "grafana:index/dashboard:Dashboard":
		r = &Dashboard{}
	case "grafana:index/dashboardPermission:DashboardPermission":
		r = &DashboardPermission{}
	case "grafana:index/dataSource:DataSource":
		r = &DataSource{}
	case "grafana:index/folder:Folder":
		r = &Folder{}
	case "grafana:index/folderPermission:FolderPermission":
		r = &FolderPermission{}
	case "grafana:index/organization:Organization":
		r = &Organization{}
	case "grafana:index/role:Role":
		r = &Role{}
	case "grafana:index/team:Team":
		r = &Team{}
	case "grafana:index/teamPreferences:TeamPreferences":
		r = &TeamPreferences{}
	case "grafana:index/user:User":
		r = &User{}
	default:
		return nil, fmt.Errorf("unknown resource type: %s", typ)
	}

	err = ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return
}

type pkg struct {
	version semver.Version
}

func (p *pkg) Version() semver.Version {
	return p.version
}

func (p *pkg) ConstructProvider(ctx *pulumi.Context, name, typ, urn string) (pulumi.ProviderResource, error) {
	if typ != "pulumi:providers:grafana" {
		return nil, fmt.Errorf("unknown provider type: %s", typ)
	}

	r := &Provider{}
	err := ctx.RegisterResource(typ, name, nil, r, pulumi.URN_(urn))
	return r, err
}

func init() {
	version, err := PkgVersion()
	if err != nil {
		fmt.Printf("failed to determine package version. defaulting to v1: %v\n", err)
	}
	pulumi.RegisterResourceModule(
		"grafana",
		"index/alertNotification",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/builtinRoleAssignment",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/dashboard",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/dashboardPermission",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/dataSource",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/folder",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/folderPermission",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/organization",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/role",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/team",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/teamPreferences",
		&module{version},
	)
	pulumi.RegisterResourceModule(
		"grafana",
		"index/user",
		&module{version},
	)
	pulumi.RegisterResourcePackage(
		"grafana",
		&pkg{version},
	)
}
