// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class BuiltinRoleAssignmentRoleGetArgs : Pulumi.ResourceArgs
    {
        [Input("global")]
        public Input<bool>? Global { get; set; }

        [Input("uid", required: true)]
        public Input<string> Uid { get; set; } = null!;

        public BuiltinRoleAssignmentRoleGetArgs()
        {
        }
    }
}
