// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Grafana.Inputs
{

    public sealed class DashboardPermissionPermissionArgs : Pulumi.ResourceArgs
    {
        [Input("permission", required: true)]
        public Input<string> Permission { get; set; } = null!;

        [Input("role")]
        public Input<string>? Role { get; set; }

        [Input("teamId")]
        public Input<int>? TeamId { get; set; }

        [Input("userId")]
        public Input<int>? UserId { get; set; }

        public DashboardPermissionPermissionArgs()
        {
        }
    }
}
