// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class AlertNotification extends pulumi.CustomResource {
    /**
     * Get an existing AlertNotification resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: AlertNotificationState, opts?: pulumi.CustomResourceOptions): AlertNotification {
        return new AlertNotification(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'grafana:index/alertNotification:AlertNotification';

    /**
     * Returns true if the given object is an instance of AlertNotification.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is AlertNotification {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === AlertNotification.__pulumiType;
    }

    /**
     * Whether to disable sending resolve messages.
     */
    public readonly disableResolveMessage!: pulumi.Output<boolean | undefined>;
    /**
     * Frequency of alert reminders. Frequency must be set if reminders are enabled.
     */
    public readonly frequency!: pulumi.Output<string | undefined>;
    /**
     * Is this the default channel for all your alerts.
     */
    public readonly isDefault!: pulumi.Output<boolean | undefined>;
    /**
     * The name of the alert notification channel.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Additional secure settings, for full reference lookup [Grafana Supported Settings
     * documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#supported-settings).
     */
    public readonly secureSettings!: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * Whether to send reminders for triggered alerts.
     */
    public readonly sendReminder!: pulumi.Output<boolean | undefined>;
    /**
     * Additional settings, for full reference see [Grafana HTTP API
     * documentation](https://grafana.com/docs/grafana/latest/http_api/alerting_notification_channels/).
     */
    public readonly settings!: pulumi.Output<{[key: string]: any} | undefined>;
    /**
     * The type of the alert notification channel.
     */
    public readonly type!: pulumi.Output<string>;
    /**
     * Unique identifier. If unset, this will be automatically generated.
     */
    public readonly uid!: pulumi.Output<string>;

    /**
     * Create a AlertNotification resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: AlertNotificationArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: AlertNotificationArgs | AlertNotificationState, opts?: pulumi.CustomResourceOptions) {
        let inputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as AlertNotificationState | undefined;
            inputs["disableResolveMessage"] = state ? state.disableResolveMessage : undefined;
            inputs["frequency"] = state ? state.frequency : undefined;
            inputs["isDefault"] = state ? state.isDefault : undefined;
            inputs["name"] = state ? state.name : undefined;
            inputs["secureSettings"] = state ? state.secureSettings : undefined;
            inputs["sendReminder"] = state ? state.sendReminder : undefined;
            inputs["settings"] = state ? state.settings : undefined;
            inputs["type"] = state ? state.type : undefined;
            inputs["uid"] = state ? state.uid : undefined;
        } else {
            const args = argsOrState as AlertNotificationArgs | undefined;
            if ((!args || args.type === undefined) && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            inputs["disableResolveMessage"] = args ? args.disableResolveMessage : undefined;
            inputs["frequency"] = args ? args.frequency : undefined;
            inputs["isDefault"] = args ? args.isDefault : undefined;
            inputs["name"] = args ? args.name : undefined;
            inputs["secureSettings"] = args ? args.secureSettings : undefined;
            inputs["sendReminder"] = args ? args.sendReminder : undefined;
            inputs["settings"] = args ? args.settings : undefined;
            inputs["type"] = args ? args.type : undefined;
            inputs["uid"] = args ? args.uid : undefined;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(AlertNotification.__pulumiType, name, inputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering AlertNotification resources.
 */
export interface AlertNotificationState {
    /**
     * Whether to disable sending resolve messages.
     */
    disableResolveMessage?: pulumi.Input<boolean>;
    /**
     * Frequency of alert reminders. Frequency must be set if reminders are enabled.
     */
    frequency?: pulumi.Input<string>;
    /**
     * Is this the default channel for all your alerts.
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * The name of the alert notification channel.
     */
    name?: pulumi.Input<string>;
    /**
     * Additional secure settings, for full reference lookup [Grafana Supported Settings
     * documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#supported-settings).
     */
    secureSettings?: pulumi.Input<{[key: string]: any}>;
    /**
     * Whether to send reminders for triggered alerts.
     */
    sendReminder?: pulumi.Input<boolean>;
    /**
     * Additional settings, for full reference see [Grafana HTTP API
     * documentation](https://grafana.com/docs/grafana/latest/http_api/alerting_notification_channels/).
     */
    settings?: pulumi.Input<{[key: string]: any}>;
    /**
     * The type of the alert notification channel.
     */
    type?: pulumi.Input<string>;
    /**
     * Unique identifier. If unset, this will be automatically generated.
     */
    uid?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a AlertNotification resource.
 */
export interface AlertNotificationArgs {
    /**
     * Whether to disable sending resolve messages.
     */
    disableResolveMessage?: pulumi.Input<boolean>;
    /**
     * Frequency of alert reminders. Frequency must be set if reminders are enabled.
     */
    frequency?: pulumi.Input<string>;
    /**
     * Is this the default channel for all your alerts.
     */
    isDefault?: pulumi.Input<boolean>;
    /**
     * The name of the alert notification channel.
     */
    name?: pulumi.Input<string>;
    /**
     * Additional secure settings, for full reference lookup [Grafana Supported Settings
     * documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#supported-settings).
     */
    secureSettings?: pulumi.Input<{[key: string]: any}>;
    /**
     * Whether to send reminders for triggered alerts.
     */
    sendReminder?: pulumi.Input<boolean>;
    /**
     * Additional settings, for full reference see [Grafana HTTP API
     * documentation](https://grafana.com/docs/grafana/latest/http_api/alerting_notification_channels/).
     */
    settings?: pulumi.Input<{[key: string]: any}>;
    /**
     * The type of the alert notification channel.
     */
    type: pulumi.Input<string>;
    /**
     * Unique identifier. If unset, this will be automatically generated.
     */
    uid?: pulumi.Input<string>;
}
